// Municipality email domain validator for Swedish government organizations
// Auto-generated from municipality data

// Municipality domains extracted from official data
export const municipalityDomains = new Set([
  'ale.se',
  'alingsas.se',
  'alvesta.se',
  'aneby.se',
  'arboga.se',
  'arjeplog.se',
  'arvidsjaur.se',
  'arvika.se',
  'askersund.se',
  'avesta.se',
  'bengtsfors.se',
  'berg.se',
  'bjurholm.se',
  'bjuv.se',
  'boden.se',
  'bollebygd.se',
  'bollnas.se',
  'borgholm.se',
  'borlange.se',
  'boras.se',
  'botkyrka.se',
  'boxholm.se',
  'bromolla.se',
  'bracke.se',
  'burlov.se',
  'bastad.se',
  'dalsed.se',
  'danderyd.se',
  'degerfors.se',
  'dorotea.se',
  'eda.se',
  'ekero.se',
  'eksjo.se',
  'emmaboda.se',
  'enkoping.se',
  'eskilstuna.se',
  'eslov.se',
  'essunga.se',
  'fagersta.se',
  'falkenberg.se',
  'falkoping.se',
  'falun.se',
  'filipstad.se',
  'finspang.se',
  'flen.se',
  'forshaga.se',
  'fargelanda.se',
  'gagnef.se',
  'gislaved.se',
  'gnesta.se',
  'gnosjo.se',
  'grums.se',
  'grastorp.se',
  'gullspang.se',
  'gallivare.se',
  'gavle.se',
  'goteborg.se',
  'stadshuset.goteborg.se',
  'gotene.se',
  'habokommun.se',
  'habo.se',
  'hagfors.se',
  'hallsberg.se',
  'hallstahammar.se',
  'halmstad.se',
  'hammaro.se',
  'haninge.se',
  'haparanda.se',
  'heby.se',
  'hedemora.se',
  'helsingborg.se',
  'herrljunga.se',
  'hjo.se',
  'hofors.se',
  'huddinge.se',
  'hudiksvall.se',
  'hultsfred.se',
  'hylte.se',
  'hellefors.se',
  'herjedalen.se',
  'harnosand.se',
  'harryda.se',
  'hassleholm.se',
  'hoganas.se',
  'hogsby.se',
  'horby.se',
  'hoor.se',
  'jokkmokk.se',
  'jarfalla.se',
  'jonkoping.se',
  'kalix.se',
  'kalmar.se',
  'karlsborg.se',
  'karlshamn.se',
  'karlskoga.se',
  'karlskrona.se',
  'karlstad.se',
  'katrineholm.se',
  'kil.se',
  'kinda.se',
  'kiruna.se',
  'klippan.se',
  'knivsta.se',
  'kramfors.se',
  'kristianstad.se',
  'kristinehamn.se',
  'krokom.se',
  'kumla.se',
  'kungsbacka.se',
  'kungsor.se',
  'kungalv.se',
  'kavlinge.se',
  'koping.se',
  'laholm.se',
  'landskrona.se',
  'laxa.se',
  'lekeberg.se',
  'leksand.se',
  'lerum.se',
  'lessebo.se',
  'lidingo.se',
  'lidkoping.se',
  'lillaedet.se',
  'lindesberg.se',
  'linkoping.se',
  'ljungby.se',
  'ljusdal.se',
  'ljusnarsberg.se',
  'lomma.se',
  'ludvika.se',
  'lulea.se',
  'lund.se',
  'lycksele.se',
  'lysekil.se',
  'malmo.se',
  'malung-salen.se',
  'mala.se',
  'mariestad.se',
  'markaryd.se',
  'mark.se',
  'mellerud.se',
  'mjolby.se',
  'mora.se',
  'motala.se',
  'mullsjo.se',
  'munkedal.se',
  'munkfors.se',
  'molndal.se',
  'monsteras.se',
  'morbylanga.se',
  'nacka.se',
  'nora.se',
  'norberg.se',
  'nordanstig.se',
  'nordmaling.se',
  'norrkoping.se',
  'norrtalje.se',
  'norsjo.se',
  'nybro.se',
  'nykvarn.se',
  'nykoping.se',
  'nynashamn.se',
  'nassjo.se',
  'ockelbo.se',
  'olofstrom.se',
  'orsa.se',
  'orust.se',
  'osby.se',
  'oskarshamn.se',
  'ovanaker.se',
  'oxelosund.se',
  'pajala.se',
  'partille.se',
  'perstorp.se',
  'pitea.se',
  'ragunda.se',
  'gotland.se',
  'robertsfors.se',
  'ronneby.se',
  'rattvik.se',
  'sala.se',
  'salem.se',
  'sandviken.se',
  'sigtuna.se',
  'simrishamn.se',
  'sjobo.se',
  'skara.se',
  'skelleftea.se',
  'skinnskatteberg.se',
  'skurup.se',
  'skovde.se',
  'smedjebacken.se',
  'solleftea.se',
  'sollentuna.se',
  'solna.se',
  'sorsele.se',
  'sotenas.se',
  'staffanstorp.se',
  'stenungsund.se',
  'stockholm.se',
  'storfors.se',
  'storuman.se',
  'strangnas.se',
  'stromstad.se',
  'stromsund.se',
  'sundbyberg.se',
  'sundsvall.se',
  'sunne.se',
  'surahammar.se',
  'svalov.se',
  'svedala.se',
  'svenljunga.se',
  'saffle.se',
  'sater.se',
  'savsjo.se',
  'soderhamn.se',
  'soderkoping.se',
  'sodertalje.se',
  'solvesborg.se',
  'tanum.se',
  'tibro.se',
  'tidaholm.se',
  'tierp.se',
  'timra.se',
  'tingsryd.se',
  'tjorn.se',
  'tomelilla.se',
  'torsby.se',
  'torsas.se',
  'tranemo.se',
  'tranas.se',
  'trelleborg.se',
  'trollhattan.se',
  'trosa.se',
  'tyreso.se',
  'taby.se',
  'toreboda.se',
  'uddevalla.se',
  'ulricehamn.se',
  'umea.se',
  'upplandsvasby.se',
  'upplands-bro.se',
  'uppsala.se',
  'uppvidinge.se',
  'vadstena.se',
  'vaggeryd.se',
  'valdemarsvik.se',
  'vallentuna.se',
  'vansbro.se',
  'vara.se',
  'varberg.se',
  'vaxholm.se',
  'vellinge.se',
  'vetlanda.se',
  'vilhelmina.se',
  'vimmerby.se',
  'vindeln.se',
  'vingaker.se',
  'vargarda.se',
  'vanersborg.se',
  'vannas.se',
  'varmdo.se',
  'varnamo.se',
  'vastervik.se',
  'vasteras.se',
  'vaxjo.se',
  'ydre.se',
  'ystad.se',
  'amal.se',
  'ange.se',
  'are.se',
  'arjang.se',
  'asele.se',
  'astorp.se',
  'atvidaberg.se',
  'almhult.se',
  'alvdalen.se',
  'alvkarleby.se',
  'alvsbyn.se',
  'engelholm.se',
  'ockero.se',
  'odeshog.se',
  'orebro.se',
  'orkelljunga.se',
  'ornskoldsvik.se',
  'ostersund.se',
  'osteraker.se',
  'osthammar.se',
  'ostragoinge.se',
  'overkalix.se',
  'overtornea.se'
])

// Swedish government agencies and regions
export const agencyDomains = new Set([
  // National agencies
  'skatteverket.se',
  'forsakringskassan.se',
  'arbetsformedlingen.se',
  'transportstyrelsen.se',
  'migrationsverket.se',
  'domstol.se',
  'polisen.se',
  'kronofogden.se',
  'lantmateriet.se',
  'naturvardsverket.se',
  'pensionsmyndigheten.se',
  'trafikverket.se',
  'sjv.se', // Jordbruksverket
  'socialstyrelsen.se',
  'folkhalsomyndigheten.se',
  'msb.se', // Myndigheten för samhällsskydd och beredskap
  'kammarkollegiet.se',
  'scb.se', // Statistiska centralbyrån
  'riksrevisionen.se',
  'skolverket.se',
  'skolinspektionen.se',
  'uka.se', // Universitetskanslersämbetet
  'vr.se', // Vetenskapsrådet
  'raa.se', // Riksantikvarieämbetet
  'kulturradet.se',
  'konsumentverket.se',
  'bolagsverket.se',
  'prv.se', // Patent- och registreringsverket
  'energimyndigheten.se',
  'havochvatten.se',
  'smhi.se',
  'sgu.se', // Sveriges geologiska undersökning
  'lakemedelsverket.se',
  'ehalsomyndigheten.se',
  'isp.se', // Myndigheten för inspektionen för socialförsäkringen
  'tillvaxtverket.se',
  'vinnova.se',
  'rymdstyrelsen.se',
  'sida.se',
  'fi.se', // Finansinspektionen
  'riksgalden.se',
  'upphandlingsmyndigheten.se',
  'konkurrensverket.se',
  'datainspektionen.se',
  'imy.se', // Integritetsskyddsmyndigheten
  'pts.se', // Post- och telestyrelsen
  'ei.se', // Energimarknadsinspektionen
  'kriminalvarden.se',
  'aklagare.se',
  'ekobrottsmyndigheten.se',
  'sakerhetspolisen.se',
  'tullverket.se',
  'kustbevakningen.se',
  'forsvarsmakten.se',
  'fmv.se', // Försvarets materielverk
  'foi.se', // Totalförsvarets forskningsinstitut
  'fhs.se', // Försvarshögskolan
  'ra.se', // Riksarkivet
  'kb.se', // Kungliga biblioteket
  
  // Regional governments (from official mail list)
  'gotland.se',
  'kronoberg.se',
  'norrbotten.se',
  'regionblekinge.se',
  'regiondalarna.se',
  'regiongavleborg.se',
  'regionhalland.se',
  'regionjh.se',
  'regionkalmar.se',
  'regionorebrolan.se',
  'regionostergotland.se',
  'regionsormland.se',
  'regionstockholm.se',
  'regionuppsala.se',
  'regionvarmland.se',
  'regionvasterbotten.se',
  'regionvastmanland.se',
  'rjl.se',
  'rvn.se',
  'skane.se',
  'vgregion.se'
])

/**
 * Validates if an email belongs to a Swedish government organization
 * @param email - Email address to validate
 * @returns true if email is from a valid Swedish government domain
 */
export function isValidGovEmail(email: string): boolean {
  if (!email || typeof email !== 'string') return false
  
  const emailLower = email.toLowerCase().trim()
  const domain = emailLower.split('@')[1]
  
  if (!domain || !domain.endsWith('.se')) return false
  
  return municipalityDomains.has(domain) || agencyDomains.has(domain)
}

/**
 * Extracts the domain from an email address
 * @param email - Email address
 * @returns domain or null if invalid
 */
export function getDomainFromEmail(email: string): string | null {
  if (!email || typeof email !== 'string') return null
  
  const parts = email.toLowerCase().trim().split('@')
  if (parts.length !== 2) return null
  
  return parts[1]
}

/**
 * Gets organization type from email domain
 * @param email - Email address
 * @returns 'municipality', 'agency', or null
 */
export function getOrganizationType(email: string): 'municipality' | 'agency' | null {
  const domain = getDomainFromEmail(email)
  if (!domain) return null
  
  if (municipalityDomains.has(domain)) return 'municipality'
  if (agencyDomains.has(domain)) return 'agency'
  
  return null
}